### ISSUE TITLE
Custom Image URL not working

### ISSUE THREAD

**Issue by ghost** [georgeduckett/TeamCoding#12]
Whenever I try to use an image URL, be it from Google Drive or directly from google images, it yields an exception and doesn't modify my image.

**### Team Coding Output**
7/21/2017 12:08:27 PM UserImageCache.SetImageSource:System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: The component cannot be found. (Exception from HRESULT: 0x88982F50)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapDecoder.Create(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption)
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapFrame.Create(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption)
   at TeamCoding.VisualStudio.UserImageCache.<>c__DisplayClass10_0.<<SetImageSource>b__0>d.MoveNext() in C:\projects\teamcoding\TeamCoding\VisualStudio\UserImageCache.cs:line 119
7/21/2017 12:08:28 PM CachedFailoverIdentityProvider.GetIdentity:CachedFailoverIdentityProvider: Got identity from VSOptionsIdentityProvider

**Comment by georgeduckett** [comment]
Thanks for the report. Have you got an example url that gives you this exception?

**Comment by ghost** [comment]
https://lh4.googleusercontent.com/5Cz5lo4Aacyf95Edun98AamWkuaJvWqTGho9BpKb5hlFzl6v9fZ84CVsz327sMDDdv6ezYo9RmguddY=w1150-h631-rw

**Comment by georgeduckett** [comment]
I tried that url myself in a browser and got a 403 (forbidden) error message from Google so that'll be the cause of the problem. You could rehost the image somewhere publicly accessible to solve your immediate problem.

I'll keep this issue open though as it would be good to improve the error reporting.

**Comment by ghost** [comment]
I just tried with some image from the web, now it works. I'm an idiot. Thanks anyways!

**Comment by ghost** [comment]
However, I have noticed that not all images from the web work. Do the images have to be of a certain file type?

**Comment by georgeduckett** [comment]
There probably are only certain file types supported (by ImageSource). When I'm improving the error reporting I'll take a look at that too.

**Comment by georgeduckett** [comment]
I've published an update (v1.0.368) that adds user image url checking to the options screen (similar to the persistence options checking) which should show what the issue is. There should also be better logging in the TeamCoding output window.
