### ISSUE TITLE
System.ArgumentNullException thrown in CachedSourceControlRepository.GetRepoDocInfo

### ISSUE THREAD

**Issue by MatthewSteeples** [georgeduckett/TeamCoding#4]
### Installed product versions
- Visual Studio: 2017 Enterprise RC
- This extension: 0.8.286

### Description
Exception is thrown which crashes Visual Studio when loading up some .cshtml files
Value cannot be null, Parameter name: key

### Steps to recreate (I've a feeling this is specific to our solution)
1. Open up Solution
2. Navigate to a .cshtml file (or sometimes a .cs file)
3. Visual Studio crashes

### Team Coding Output
Not able to grab this easily unless it's output to a file somewhere?

### Exception Stacktrace
`   at System.Collections.Generic.Dictionary``2.FindEntry(TKey key)
   at TeamCoding.Documents.SourceControlRepositories.CachedSourceControlRepository.GetRepoDocInfo(String fullFilePath) in C:\projects\teamcoding\TeamCoding\Documents\SourceControlRepositories\CachedSourceControlRepository.cs:line 20
   at TeamCoding.VisualStudio.TeamCodingTextViewConnectionListener.&amp;lt;SubjectBuffersConnected&amp;gt;d__3.MoveNext() in C:\projects\teamcoding\TeamCoding\VisualStudio\TeamCodingTextViewConnectionListener.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&amp;lt;&amp;gt;c.&amp;lt;ThrowAsync&amp;gt;b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)`

**Comment by MatthewSteeples** [comment]
We're still seeing this issue on the latest build (0.8.289)

**Comment by georgeduckett** [comment]
Thanks. I was actually just updating something unrelated (updating to latest VS2017 DLLs). I've not had much chance at tackling this issue yet; I've not forgotten about it though.

**Comment by MatthewSteeples** [comment]
@georgeduckett Thanks for letting us know. If there's anything we can do to help diagnose then let us know. If you don't get round to it before then I'm hoping to download the source at the weekend and have a go at it myself

**Comment by georgeduckett** [comment]
@MatthewSteeples I've managed to take a look at this and hopefully have fixed it (at least one case anyway).

I reproduced the issue locally by opening an `aspx` file. The issue in that case was that the text buffer was a projection buffer, rather than just a simple `ITextBuffer` over a file. A projection buffer is a combination of multiple text buffers. In the `aspx` case it's actually a projection buffer with only a single underlying text buffer which makes things simple to handle. For now I'm just taking the text file of the first underlying buffer, however really I should change things to correctly show the user opening multiple files when they are combined into one projection buffer that the user views. I'd be interested in finding a case where that happens (projection buffer consisting of multiple source files).

**Comment by MatthewSteeples** [comment]
@georgeduckett Sounds like a good change. When you get chance do you mind releasing it and we'll give it a go?

**Comment by georgeduckett** [comment]
@MatthewSteeples Just released now. Update won't appear instantly in the marketplace, but shouldn't take long to appear. Please let me know how you get on.

**Comment by MatthewSteeples** [comment]
That particular instance of the exception has been fixed, but I now get the same exception in a slightly different area:

1. Right click on a method call and select "find all references"
2. In the references window, single or double click on one of the items
3. Exception is thrown

Hope that's enough to track it down.

**Comment by MatthewSteeples** [comment]
(I'm now on 2017 Release, version 1.0.305 of the extension)

**Comment by georgeduckett** [comment]
@MatthewSteeples I've tried to reproduce the error but haven't had any luck. It shouldn't matter how the file is opened (via find all references or just opening it from the solution explorer). A few questions:  
Is the latest crash's stacktrace the same as above?
Is it consistently crashing for certain files, or does it sometimes open them ok?
Is it only erroring with a certain file type?  
Anything in common with the files it crashes with (same file extension, project type, type of editor displayed etc)?

In the meantime I have made a change (assuming the stacktrace is the same), introducing a fallback method of getting a filepath when a view into a file is opened. It will also log the error (in the TeamCoding output window) and ignore the problem document so it shouldn't crash anymore.

If you could update (1.0.309 or above), answer some of the questions above if you can and paste in anything relevant that appears in the TeamCoding output wouldn't that would help a lot.

**Comment by MatthewSteeples** [comment]
I checkout out the source and tried running it locally in the debugger (before your change) and was also unable to reproduce it, which is very strange. The StackTrace was the same as previously mentioned (which is why I kept the same issue) and it consistently happens on cs files. I've not managed to get Find All References to highlight any other types of files.

The change has stopped VS from crashing, and I now get the popup telling me to look in the XML file for the logs. The exception in there is similar, and there is a secondary error as well. This only gets thrown once and then I'm able to carry on working.

I don't know whether this is likely to help or not, but it appears to be the highlight window that pops up that causes the exception, not the opening of the file itself.

![image](https://cloud.githubusercontent.com/assets/255971/23751692/58cc032a-04ca-11e7-9a29-0b1e1f4bb793.png)

I'm investigating now and seeing if I can reproduce it in a debugger environment. It could be that we have a conflicting extension that is causing the error.

**Comment by MatthewSteeples** [comment]
Got it. It is that peek preview window. It doesn't have a ITextDocument property so returns an empty enumerable from TextBufferExtensions.GetTextDocumentFilePaths.

For some details, the preview window has a ContentType of RoslynPreviewContentType (as opposed to the text files having CSharp) and the ITextBuffer is actually a ElisionBuffer instead of a TextBuffer.

I think it's acceptable in this scenario to just stop when the filepath is null (as opposed to error), as there's nothing left to process.

To get the preview window to appear, you need to hover over the actual bit of code in the Find All References window (not the filename, line number etc).

I'll put together a PR with my suggested changes and you can see what you think

**Comment by georgeduckett** [comment]
Ahh. Thanks for the debugging and for the pull request. Happy for me to close this issue, or are you getting any other instances of this?

**Comment by MatthewSteeples** [comment]
I gave it a brief runaround in the experimental hive and didn't get any further instances of it so I'll close it for now. I've a feeling the change is a generic fix for any instance where a filepath isn't available. More than happy to help out with these things where we can. As a completely remote team I can see us using this quite a bit!
