### ISSUE TITLE
NullReference on project load

### ISSUE THREAD

**Issue by MatthewSteeples** [georgeduckett/TeamCoding#6]
You can tell we're starting to use this in earnest now...!

Following stacktrace occurs while the solution is still loading (so I'm guessing everything that needs to be initialised isn't yet initialised). Will try and have a look myself in a couple of hours.

    System.NullReferenceException occurred
    HResult=0x80004003
    Message=Object reference not set to an instance of an object.
    Source=TeamCoding
    StackTrace:
    at TeamCoding.Documents.SourceControlRepositories.GitRepository.GetRepoDocInfo(String fullFilePath)
    at TeamCoding.Documents.SourceControlRepositories.CachedSourceControlRepository.GetRepoDocInfo(String fullFilePath)
    at TeamCoding.VisualStudio.TeamCodingTextViewConnectionListener.<SubjectBuffersConnected>d__3.MoveNext()
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
    at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
    at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.<>c.<.cctor>b__20_0(Object state)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Windows.Threading.DispatcherOperation.Invoke()
    at System.Windows.Threading.Dispatcher.ProcessQueue()
    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by georgeduckett** [comment]
Happy to see it's starting to get some use!
Re that error, possibly it's something that's not yet initialised, although the method is relatively self-contained. It's also possible that there's something about your Git setup that's causing the problem. (I'm fairly new to Git so haven't tested extensive scenarios).

I've tried to reproduce the issue but no luck; possibly it's a race-condition somewhere if it is an initialisation bug. If you can repro in the debugger I'm happy to take a look, or if you've got the time/inclination happy for you to submit a pull request.

**Comment by MatthewSteeples** [comment]
I've not seen this error since the other day. I think you're right that it's a race condition, but reproducing it is probably going to be tricky. I'd imagine that the machine was under heavy load at the time, which is why the git component took longer to initialise so wasn't ready for TeamCoding to use it.
